version: '3.1'

services:
  mongo:
    container_name: 'mongo'
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_ROOT_DATABASE: taskflow
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'
    networks:
      - local

  mongo-express:
    container_name: 'mongo-express'
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017
      ME_CONFIG_BASICAUTH: false
    ports:
      - '8081:8081'
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
  mongo_data: