spring:
  application:
    name: Task Flow
  data:
    mongodb:
      authentication-database: false
      username: admin
      password: admin
      host: localhost
      port: 27017
  graphql:
    graphiql:
      enabled: true

server:
  port: 8080